ALTER TABLE "CartItem"
ADD COLUMN "isFreeDrink" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Order"
ADD COLUMN "freeDrinksRedeemed" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "OrderItem"
ADD COLUMN "isFreeDrink" BOOLEAN NOT NULL DEFAULT false;
